# Generated by Django 3.2.8 on 2021-10-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('site_title', models.CharField(max_length=60, verbose_name='Title')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('inventory', models.IntegerField(verbose_name='Inventory')),
                ('tags', models.JSONField(verbose_name='Tags')),
                ('popularity', models.IntegerField(verbose_name='Popularity')),
                ('picture1', models.ImageField(upload_to=None, verbose_name='Image 1')),
                ('picture2', models.ImageField(blank=True, upload_to=None, verbose_name='Image 2')),
                ('picture3', models.ImageField(blank=True, upload_to=None, verbose_name='Image 3')),
                ('picture4', models.ImageField(blank=True, upload_to=None, verbose_name='Image 4')),
                ('picture5', models.ImageField(blank=True, upload_to=None, verbose_name='Image 5')),
                ('picture6', models.ImageField(blank=True, upload_to=None, verbose_name='Image 6')),
                ('review_count', models.IntegerField(verbose_name='Review Count')),
                ('rating_count', models.IntegerField(verbose_name='Rating Count')),
                ('average_rating', models.IntegerField(verbose_name='Average Rating')),
                ('reviews_ratings', models.JSONField(verbose_name='Reviews and Ratings')),
            ],
        ),
    ]
