# Generated by Django 3.2.4 on 2021-10-25 05:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture1',
            field=models.ImageField(upload_to='images/', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture2',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture3',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture4',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture5',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture6',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image 6'),
        ),
        migrations.CreateModel(
            name='ReviewsRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Rating')),
                ('review', models.CharField(blank=True, max_length=250, null=True, verbose_name='Review')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
