# Generated by Django 3.2.7 on 2021-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(to='products.subcategories'),
        ),
    ]
