# Generated by Django 3.2.8 on 2021-10-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
