# Generated by Django 3.2.4 on 2021-11-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_addresses_cart_cartitem_customer_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
