# Generated by Django 3.2.8 on 2021-11-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_addresses_cart_cartitem_customer_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
