# Generated by Django 3.2.8 on 2021-11-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='site_title',
        ),
    ]
